# Generated by Django 3.2.8 on 2021-10-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterPDF_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='name',
        ),
        migrations.AlterField(
            model_name='pdf',
            name='pdf_uploaded',
            field=models.FileField(upload_to=''),
        ),
    ]
